//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvolutionV1._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorySearch
    {
        public int SearchId { get; set; }
        public string NameSearch { get; set; }
        public string Price { get; set; }
    
        public virtual UserProfil UserProfil { get; set; }
        public virtual RateItems RateItems { get; set; }
    }
}
