//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEvolutionV1._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfil()
        {
            this.HistorySearch = new HashSet<HistorySearch>();
        }
    
        public int UserProfilId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string StatusWork { get; set; }
        public string Number { get; set; }
        public string Age { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorySearch> HistorySearch { get; set; }
    }
}
